### ISSUE TITLE
Remarks

### ISSUE THREAD

**Issue by pnpancholi** [jooohneth/nft-collection-100#1]
1. No comments
2. Missed opportunity to use method overloading.
3. I suggest using `call` instead of `transfer` because it returns result.
4. Not a good idea to really on client to get URI if you are only working on the smart contract because they can be modified. And this makes the `baseURI` sort of redundant.

**Comment by zeroxjohn** [comment]
> 1. No comments
> 2. Missed opportunity to use method overloading.
> 3. I suggest using `call` instead of `transfer` because it returns result.
> 4. Not a good idea to really on client to get URI if you are only working on the smart contract because they can be modified. And this makes the `baseURI` sort of redundant.

Modified the contract with your suggestions. Thanks! Let me know if there are any more suggestions.
